"""Atualiza trip

Revision ID: 105d8838ff91
Revises: ea7f2cbcd49c
Create Date: 2026-05-31 21:37:23.002896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105d8838ff91'
down_revision: Union[str, Sequence[str], None] = 'ea7f2cbcd49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trip', 'route_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('trip_driver_id_fkey'), 'trip', type_='foreignkey')
    op.drop_constraint(op.f('trip_route_id_fkey'), 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'user', ['driver_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trip', 'route', ['route_id'], ['route_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key(op.f('trip_route_id_fkey'), 'trip', 'route', ['route_id'], ['route_id'])
    op.create_foreign_key(op.f('trip_driver_id_fkey'), 'trip', 'user', ['driver_id'], ['user_id'])
    op.alter_column('trip', 'route_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trip', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
