"""

Revision ID: 4bad631bf7b6
Revises: cb7eb8162dfc
Create Date: 2026-06-15 18:42:42.145007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bad631bf7b6'
down_revision: Union[str, Sequence[str], None] = 'cb7eb8162dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('boarding_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('route', sa.Column('boarding_longitude', sa.Numeric(precision=11, scale=7), nullable=True))
    op.add_column('route', sa.Column('drop_off_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('route', sa.Column('drop_off_longitude', sa.Numeric(precision=11, scale=7), nullable=True))
    op.drop_column('route', 'boarding_point_coordinates')
    op.drop_column('route', 'drop_off_point_coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('drop_off_point_coordinates', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('boarding_point_coordinates', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('route', 'drop_off_longitude')
    op.drop_column('route', 'drop_off_latitude')
    op.drop_column('route', 'boarding_longitude')
    op.drop_column('route', 'boarding_latitude')
    # ### end Alembic commands ###
