"""atualiza forma de salvar coordenadas

Revision ID: 8e9650f7a721
Revises: 4bad631bf7b6
Create Date: 2026-06-15 18:43:55.916284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9650f7a721'
down_revision: Union[str, Sequence[str], None] = '4bad631bf7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
