"""adiciona campos em rota

Revision ID: cb7eb8162dfc
Revises: 105d8838ff91
Create Date: 2026-06-14 00:32:55.716170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb7eb8162dfc'
down_revision: Union[str, Sequence[str], None] = '105d8838ff91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('city_of_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('route', sa.Column('destination_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('route', sa.Column('boarding_point_coordinates', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('route', sa.Column('drop_off_point_coordinates', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'drop_off_point_coordinates')
    op.drop_column('route', 'boarding_point_coordinates')
    op.drop_column('route', 'destination_city')
    op.drop_column('route', 'city_of_origin')
    # ### end Alembic commands ###
